#!/usr/bin/perl 
$user=$ARGV[0];
system("/usr/local/sbin/tempdns $user");
system("perl -p -i -e 's/cpanel_user/$user/g' /home/$user/php.ini");
system("/bin/mkdir /home/$user/tmp/eaccelerator/");
system("/bin/mkdir /home/$user/tmp/xcache/");
system("/bin/mkdir /home/$user/tmp/apc/");
system("/bin/mkdir /etc/php-conf/$user/");
system("/bin/mkdir /usr/local/apache/conf/userdata/std/2/$user/");
## svn manager
system("/bin/mkdir /etc/svn-repos/$user/");
system("/bin/mkdir /home/$user/svn-repos/");
system("/bin/chown -R $user: /home/$user/svn-repos/");
system("/bin/chown -R $user: /etc/svn-repos/$user/");
system("/usr/local/sbin/svn_db $user");
# end svn manager
system("echo /home/$user/public_html >> /root/monitor_paths");
system("chmod 777 /home/$user/tmp");
system("/usr/local/sbin/prava");
#  SPF and DKeys installations
system ("/usr/local/cpanel/bin/domain_keys_installer $user");
system ("/usr/local/cpanel/bin/spf_installer $user");
